apiVersion: v1
kind: ConfigMap
metadata:
  name: api
  namespace: webapp
data:
  FLASK_PORT: "5000"
  FLASK_DEBUG: "0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-nginx
  namespace: webapp
data:
  default.conf: |
    server {
        listen 80;

        server_name _;

        location / {
            proxy_set_header Host $host ;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto: http;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            proxy_pass http://127.0.0.1:5000;
            proxy_read_timeout 10;
        }
    }
